import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import profileRouter from "./profile";
import adminRouter from "./admin";
import adminAIProviderRouter from "./admin-ai-provider";
import adminGlobalCompaniesRouter from "./admin-global-companies";
import billingRouter from "./billing";
import companiesRouter from "./companies";
import globalCompaniesRouter from "./global-companies";
import sendingRouter from "./sending";
import sendingReportsRouter from "./sending-reports";
import microsoft365TraceRouter from "../lib/microsoft365-trace";
import gmailMailboxRouter from "../lib/gmail-mailbox";
import { contactImportRouter } from "./contacts";
import contactFieldOptionsRouter from "./contact-field-options";
import notificationsRouter from "./notifications";
import adminNotificationsRouter from "./admin-notifications";
import supportRouter from "./support";
import maintenanceRouter from "./maintenance";

const router: IRouter = Router();
router.use(healthRouter);
router.use(authRouter);
router.use(profileRouter);
router.use(billingRouter);
router.use(companiesRouter);
router.use(globalCompaniesRouter);
router.use(contactFieldOptionsRouter);
router.use(notificationsRouter);
router.use(contactImportRouter);
router.use(sendingRouter);
router.use(sendingReportsRouter);
router.use(microsoft365TraceRouter);
router.use(gmailMailboxRouter);
router.use(adminRouter);
router.use(adminGlobalCompaniesRouter);
router.use(adminAIProviderRouter);
router.use(adminNotificationsRouter);
router.use(supportRouter);
router.use(maintenanceRouter);
export default router;
