// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/mailflow-overview/Current.tsx": () => import("../components/mockups/mailflow-overview/Current.tsx"),
  "./components/mockups/mailflow-overview/Redesigned.tsx": () => import("../components/mockups/mailflow-overview/Redesigned.tsx")
};
